# Netlify Configuration for Kolossus.org
# Ensures immediate functionality on deployment

[build]
  # Build command
  command = "npm run build"
  
  # Build output directory
  publish = "dist/public"
  
  # Node version
  environment = { NODE_VERSION = "18" }

[build.processing]
  # Skip processing for faster deployment
  skip_processing = false

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# API redirects (fallback to demo when backend unavailable)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
# Enable Edge Functions for demo mode
[[edge_functions]]
  function = "demo-api"
  path = "/api/*"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.openai.com https://*.netlify.app"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for production
[context.production.environment]
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_ENABLE_DEMO = "true"
  REACT_APP_DOMAIN = "kolossus.org"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  REACT_APP_ENVIRONMENT = "staging"
  REACT_APP_ENABLE_DEMO = "true"

# Environment variables for deploy previews
[context.deploy-preview.environment]
  REACT_APP_ENVIRONMENT = "staging"
  REACT_APP_ENABLE_DEMO = "true"